title: Ttokdok API Book
author: Heekang Park
email: park.heekang33@gmail.com
description: API Book for Ttokdok by Moai
version: 1.0.0
baseurl: "/docs"
url: ""
exclude: ["run", "commit", "README.md", "LICENSE", ".gitignore", "sync_html.py"]
assets: /assets
data_dir: _api
includes_dir: _includes
layouts_dir: _layouts
collections_dir: documents
api_baseurl: "http://localhost:7002"

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

collections:
  api_book_page:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
      type: "api_book_page"
    values:
      layout: "api"